Draggability, preliminary commit
BrandonDenham/trova-components pull request #21
Opened 2020-12-21 20:16 UTC by andres-arista

This is a very barebones commit, I couldn't yet understand some aspects on implementing draggability so I couldn't make a lot of progress. Hope this is somewhat useful though!

2021-01-06 19:50 UTC, federicorufrancos commented
Here is the new version of draggable components.
Need some extra work the interfaces and adjust some styling details.

2021-01-07 06:30 UTC, BrandonDenham requested changes

2021-01-07 06:30 UTC, BrandonDenham commented on package-lock.json
> +        "@react-dnd/asap": {
this will be a conflict as i switched it to yarn.lock

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggable.stories.tsx
> +                <Button
so there should be no need to embed a Button in a DraggableButton.  This button should be in the DraggableButton's implementation

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggable.stories.tsx
> +                <Button
this nesting should happen inside draddableButton, and the draggableButton would pass the props to the Button

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggableButton styles.tsx
> +export const draggableButton =() => css`
prettier should be run

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggableButton.tsx
> +import React from 'react';
fileName should be capitalized

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggableButton.tsx
> +		collect: (monitor: DragSourceMonitor) => ({
this is dummy data right but should be using the collect stuff passed in?

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggableButton.tsx
> +		<div ref={drag} css={draggableButton()}>
i don't think we need a div all this should just be on the button.  There are no children in the DraggableButton, it just uses the Button and has draggable data

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/draggableCard.tsx
> +      			<p>Drop here</p>
assuming this is still WIP, same issues with nesting and all that

2021-01-07 06:30 UTC, BrandonDenham commented on src/components/draggable/index.ts
> +export { DraggableContainer, DraggableTarget, DraggableCard, DraggableButton };
can you take a closer look at the desired exports.  We want DraggableCard and DraggableButton to be next to Button/Card and exported from there, 

Not from the Draggable directory

2021-01-07 14:00 UTC, federicorufrancos commented on src/components/draggable/draggableButton.tsx
> +		collect: (monitor: DragSourceMonitor) => ({
So Collect return the object been dragged and its state. Inside this function I just add now onCollect as callback of what's been doing
EX: 
```
const [{ **opacity** }, drag, preview] = useDrag({
collect: (monitor) => ({
	**opacity**: monitor.isDragging() ? 0.4 : 1,
}),
return (
<div ref={preview} style={{ ...style, **opacity** }}></div>)

```

2021-01-08 16:34 UTC, BrandonDenham approved these changes
Some changes, but i think that can take you through to be done

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableTarget.tsx
> +            <P>{children}</P>
do we need the<P> tag? that feel like it will apply unnecessary formatting

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableButton.tsx
> +    const specs = {
depending on how useDrag works, this might be best in a useMemo

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableButton.tsx
> +    const specs = {
so we could create our own "useDragSpecs" and "useDropSpecs"  and export them from Draggable. this  should make implementing other Draggable Components really simple in the future

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableButton.tsx
> +        <div ref={drag}>
is it possible to add the drag ref directly to the button?  then we could get rid of this div

the button may need to be modified with a forwardRef - https://reactjs.org/docs/forwarding-refs.html 

But that will keep the html more shallow

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableCard.tsx
> +        <div ref={dragAndDrop}>
same here regarding the dragAndDropRef and the card, would be better if we can forward the ref to the underlying component

2021-01-08 16:34 UTC, BrandonDenham commented on src/components/draggable/DraggableCard.tsx
> +    const [collectedDragProps, drag] = useDrag(dragSpecs);
same comment as above on combining all this into our own custom hook,  
since you can combine with useDrag,  the best name would probably be:

useDragRef
useDropRef

2021-01-08 17:21 UTC, federicorufrancos commented on src/components/draggable/index.ts
> +export { DraggableContainer, DraggableTarget, DraggableCard, DraggableButton };
@BrandonDenham so I have to move DraggableCard.txs inside card folder? and inside Card index.ts export this draggableCard? Or just import DraggableCard from draggable folder?
Finally Storybook draggableCard sample should be inside Card?

2021-01-11 16:36 UTC, merged