Number component creation
BrandonDenham/trova-components pull request #32
Opened 2021-01-27 16:24 UTC by andres-arista

Closes #31

2021-01-28 08:49 UTC, BrandonDenham requested changes

2021-01-28 08:49 UTC, BrandonDenham commented on src/components/number/Number.tsx
> +    handleAdd,
these shouldn't be add and subtract as props, add and subtract should call onChange

2021-01-28 08:49 UTC, BrandonDenham commented on src/components/number/Number.tsx
> +    const theme = useTheme();
They should still be able to change the value of the number by entering the value in an input by typing . . . there should be an onChange that gets called.

2021-01-28 14:36 UTC, andres-arista commented on src/components/number/Number.tsx
> +    handleAdd,
Fixed

2021-01-28 14:36 UTC, andres-arista commented on src/components/number/Number.tsx
> +    const theme = useTheme();
Fixed

2021-01-29 11:50 UTC, BrandonDenham approved these changes

2021-02-02 15:34 UTC, closed without merging