disabled button primary
BrandonDenham/trova-components pull request #53
Opened 2021-03-17 14:12 UTC by juligobbi-fluxit

2021-03-18 07:18 UTC, BrandonDenham requested changes

2021-03-18 07:18 UTC, BrandonDenham commented on src/components/button/button.styles.tsx
> +    };
are we not supporting disabled with other colors? all the button colors should be able to be disabled.

2021-03-18 07:18 UTC, BrandonDenham commented on src/components/button/button.tsx
> +            disabled = false,
in addition to changing the styles, disabling the button should prevent the onClick event from being fired:  this should be updated to: 



        const handleButtonClicked = useCallback(
            (event: SyntheticEvent) => {
                onClick && !disabled ? onClick(event, id) : event.stopPropagation();
            },
            [id, onClick, disabled]
        );

2021-03-18 14:13 UTC, juligobbi-fluxit commented on src/components/button/button.styles.tsx
> +    };
I agree, it makes sense that each button would have the disabled state. But I followed invision, where the primary button is the only one designed with a disabled state. Can those other disabled button designs be elsewhere?
https://projects.invisionapp.com/d/main#/console/20527135/434741270/preview

2021-03-19 07:17 UTC, BrandonDenham approved these changes

2021-03-19 14:52 UTC, merged